### ISSUE TITLE
High DPI Scaling - Remains at 1x

### ISSUE THREAD

**Issue by lukeco11** [SnoutBug/mmcklauncher#1]
Installed on system using 200% scaling on 4K monitor. Launcher appears at 1X. There does not appear to be a way to change this. Is there? Expected behavior would be for it to match system settings.

**Comment by SnoutBug** [comment]
Weirdly enough the launcher scales fine while testing when using 
`QT_SCALE_FACTOR=2 plasmoidviewer -a mmcklauncher -l topedge -f horizontal -x 0 -y 0 -s 1920x1080`
But I experience the same scaling issues when setting the global scale to 200%. I have no Idea what causes this any help is appreciated.

**Comment by Metaberg** [comment]
currently many elements are positioned hard code. So the elements can't scale properly. Also the default window size causes problems. 
The simplest solution would be implementing: [PlasmaCore.Units.devicePixelRatio](https://develop.kde.org/docs/extend/plasma/widget/plasma-qml-api/#plasmacoreunitsdevicepixelratio)

**Comment by SnoutBug** [comment]
Should be fixed with release [0.3](https://github.com/SnoutBug/mmcklauncher/releases/tag/0.3)
