### ISSUE TITLE
[help wanted] Unable to find any setting for custom greeting

### ISSUE THREAD

**Issue by jaamivstheworld** [SnoutBug/mmcklauncher#10]
My friend and some other people were able to set a custom greeting, but for me I see no such setting in "Configure MMcK Launcher".

**Comment by SnoutBug** [comment]
Right click the launcher on your panel and choose configure MMcK Launcher. You should be able to change the message there. If not try updating.

**Comment by jaamivstheworld** [comment]
Tried both, no luck. Any other way?

**Comment by SnoutBug** [comment]
You probably still have an old version loaded somewhere. It's in the code there is no way its not there
