### ISSUE TITLE
The menu covers the task manager which i centered using spacers.

### ISSUE THREAD

**Issue by ShaunakPemmaraju** [SnoutBug/mmcklauncher#11]
The menu upon opening covers the entire task manager which I had centered using Spacers. The panel is on autohide and the menu really screws things over when multitasking.
![image](https://user-images.githubusercontent.com/73421617/156814018-84e7c4b0-5357-4cf5-9eda-e4d567bf1b9c.png)

**Comment by SnoutBug** [comment]
Addressed in release [0.3](https://github.com/SnoutBug/mmcklauncher/releases/tag/0.3)
