### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Vistaus** [SnoutBug/mmcklauncher#12]
Translation support (esp. in the settings dialog) would be nice to have. I will provide the Dutch translation if you implement translation support. 🙂

**Comment by SnoutBug** [comment]
I've added translation support in [release 0.4](https://github.com/SnoutBug/mmcklauncher/releases/tag/0.4)

**Comment by Vistaus** [comment]
Awesome! I'll start translating right away! :)
Thank you for adding the support! :)
