### ISSUE TITLE
error loading qml file 

### ISSUE THREAD

**Issue by a-ti-k** [SnoutBug/mmcklauncher#20]
'Error loading QML file: file:///home/atik/.local/share/plasma/plasmoids/com.github.SnoutBug.mmckLauncher/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable
file:///home/atik/.local/share/plasma/plasmoids/com.github.SnoutBug.mmckLauncher/contents/ui/MenuRepresentation.qml:145:11: Type MainView unavailable
file:///home/atik/.local/share/plasma/plasmoids/com.github.SnoutBug.mmckLauncher/contents/ui/MainView.qml:19:1: module "QtQuick" version 2.15 is not installed'

when i click on the application launcher this error shows up.

**Comment by SnoutBug** [comment]
> "QtQuick" version 2.15 is not installed

I'm guessing this is the cause

**Comment by INSIDIOUS2007** [comment]
plz help sir i am getting "QtQuick" version 2.15 is not installed error

**Comment by SnoutBug** [comment]
Have you tried installing qtquick v 2.15?
