### ISSUE TITLE
Integration with Krunner

### ISSUE THREAD

**Issue by Corrupter-rot** [SnoutBug/mmcklauncher#28]
Have been using the launcher for times. Loved the design and looks. Just a suggestion if possible can you integrate the launcher with Krunner which is provided by KDE. As Krunner can search for much more including the subsettings in the settings. Make working easier.

**Comment by SnoutBug** [comment]
I really like the idea, I will def look into that when I got some more freetime!

**Comment by Corrupter-rot** [comment]
Thanks for hearing the suggestion..!

**Comment by opekope2** [comment]
I just found the solution to this with the help of [this reddit post](https://www.reddit.com/r/kde/comments/v4sxqi/plasmoid_development_use_the_enabled_krunner/):
Remove runners from [here](https://github.com/SnoutBug/mmcklauncher/blob/7ec69919a5456d140c1eb4313bd7a7641678a49e/contents/ui/main.qml#L168) to enable all configured runners.

**Comment by Corrupter-rot** [comment]
Thanks for the help. But I have now switched to WM instead of DE's.
I'll keep it in mind if I ever switched to KDE.

**Comment by opekope2** [comment]
It's merged in #39, so you can use it right as you switch to KDE :wink:
