### ISSUE TITLE
[Feature] Add option to make launcher float from panel

### ISSUE THREAD

**Issue by davigamer987** [SnoutBug/mmcklauncher#9]
So i have been looking for a kde launcher for years that floats above the panel and that looks good (I don like the windows 11 clones), I Attached a poorly made "concept" on how that would look, idk how to make rounded corners tho
![koolde](https://user-images.githubusercontent.com/68574209/156694495-eaeae9e4-3e6d-4761-bf54-c0ac4f9b866f.png)

**Comment by SnoutBug** [comment]
Moved to #3
